// atguigu/React/源码/redux_test/1_src_纯react版/components/Count/index.jsx
import React, { Component } from 'react';

export default class Count extends Component {

  state = { count: 0 };

  //加法
  increment = () => {
    const { value } = this.selectNumber;
    const { count } = this.state;
    this.setState({ count: count + value * 1 });
  };
  //减法
  decrement = () => {
    const { value } = this.selectNumber;
    const { count } = this.state;
    this.setState({ count: count - value * 1 });
  };
  //奇数再加
  incrementIfOdd = () => {
    const { value } = this.selectNumber;
    const { count } = this.state;
    if (count % 2 !== 0) {
      this.setState({ count: count + value * 1 });
    }
  };
  //异步加
  incrementAsync = () => {
    const { value } = this.selectNumber;
    const { count } = this.state;
    setTimeout(() => {
      this.setState({ count: count + value * 1 });
    }, 500);
  };

  render() {
    return (
      <div>
        <h1>当前求和为：{ this.state.count }</h1>
        <select ref={ c => this.selectNumber = c }>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>&nbsp;
        <button onClick={ this.increment }>+</button>
        &nbsp;
        <button onClick={ this.decrement }>-</button>
        &nbsp;
        <button onClick={ this.incrementIfOdd }>当前求和为奇数再加</button>
        &nbsp;
        <button onClick={ this.incrementAsync }>异步加</button>
        &nbsp;
      </div>
    );
  }
}

// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/16_src_求和案例_纯Vue版/components/Count.vue
<template>
  <div>
    <h2>当前求和为：{{ sum }}</h2>
    <select v-model.number="n">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select>&nbsp;
    <button @click="increment">+</button>&nbsp;
    <button @click="decrement">-</button>&nbsp;
    <button @click="incrementOdd">奇数再加</button>&nbsp;
    <button @click="incrementAsync">异步加</button>
  </div>
</template>

<script>
export default {
  name: 'Count',
  data() {
    return {
      sum: 0, //和
      n: 1 //n是用户选择的数字
    };
  },
  methods: {
    increment() {
      this.sum += this.n;
    },
    decrement() {
      this.sum -= this.n;
    },
    incrementOdd() {
      if (this.sum % 2) {
        this.sum += this.n;
      }
    },
    incrementAsync() {
      setTimeout(() => {
        this.sum += this.n;
      }, 500);
    },
  }
};
</script>
