// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/25_src_命名路由简化跳转和传参/App.vue
<template>
  <div>
    <Header/>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">

          <!-- 原始html中用a实现跳转页面 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a>
          <a class="list-group-item" href="./home.html">Home</a> -->

          <!-- Vue中使用router-link实现路径改变 -->
          <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
          <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <router-view></router-view>

            <!-- 若匹配多个路由组件，需要配置name属性 -->
            <!-- <router-view name="h1"></router-view>
            <router-view name="h2"></router-view> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Header from './components/Header';

export default {
  name: 'App',
  components: { Header }
};
</script>

<style>
.active {
  background-color: gray !important;
  color: orange !important;
  font-weight: bold;
}
</style>

// atguigu/React/hacker-stories/src/App.jsx
import React, { Component } from 'react';
import { Route, Switch, Redirect } from 'react-router-dom';
import Home from './pages/Home'; //Home是路由组件
import About from './pages/About'; //About是路由组件
import Header from './components/Header'; //Header是一般组件
import MyNavLink from './components/MyNavLink';

export default class App extends Component {
  render() {
    return (
      <div>
        <div className="row">
          <div className="col-xs-offset-2 col-xs-8">
            <Header/>
          </div>
        </div>
        <div className="row">
          <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
              {/* 原生html中，靠<a>跳转不同的页面 */ }
              {/* <a className="list-group-item" href="./about.html">About</a>
							<a className="list-group-item active" href="./home.html">Home</a> */ }

              {/* 在React中靠路由链接实现切换组件--编写路由链接 */ }
              <MyNavLink to="/about">About</MyNavLink>
              <MyNavLink to="/home">Home</MyNavLink>
            </div>
          </div>
          <div className="col-xs-6">
            <div className="panel">
              <div className="panel-body">
                {/* 注册路由 */ }
                <Switch>
                  <Route path="/about" component={ About }/>
                  <Route path="/home" component={ Home }/>
                  <Redirect to="/about"/>
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
