// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/23_src_路由params参数/pages/Detail.vue
<template>
  <ul>
    <!-- 获取params参数 -->
    <li>ID：{{ id }}</li>
    <li>TITLE：{{ title }}</li>
    <li>CONTENT：{{ content }}</li>
  </ul>
</template>

<script>
export default {
  name: 'Detail',
  mounted() {
    console.log(this);
  },
  computed: {
    id() {
      return this.$route.params.id;
    },
    title() {
      return this.$route.params.title;
    },
    content() {
      return this.$route.params.content;
    },
  }
};
</script>

// atguigu/React/源码/react_staging/17_src_向路由组件传递search参数/pages/Home/Message/Detail/index.jsx
import React, { Component } from 'react';
import qs from 'querystring';

const DetailData = [
  { id: '01', content: '你好，中国' },
  { id: '02', content: '你好，尚硅谷' },
  { id: '03', content: '你好，未来的自己' }
];
export default class Detail extends Component {
  render() {
    console.log(this.props);

    // 接收params参数
    // const {id,title} = this.props.match.params

    // 接收search参数
    const { search } = this.props.location;
    const { id, title } = qs.parse(search.slice(1));

    const findResult = DetailData.find((detailObj) => {
      return detailObj.id === id;
    });
    return (
      <ul>
        <li>ID:{ id }</li>
        <li>TITLE:{ title }</li>
        <li>CONTENT:{ findResult.content }</li>
      </ul>
    );
  }
}
