// atguigu/React/hacker-stories/src/pages/Home/Message/index.jsx
import React, { Component } from "react";
import { Link, Route } from "react-router-dom";
import Detail from "./Detail";
export default class Message extends Component {
  state = {
    messageArr: [
      { id: "01", title: "消息1" },
      { id: "02", title: "消息2" },
      { id: "03", title: "消息3" },
    ],
  };
  render() {
    const { messageArr } = this.state;
    return (
      <div>
        <ul>
          {messageArr.map((msgObj) => {
            return (
              <li key={msgObj.id}>
				  {/* 向路由组件传递params参数 */}
                <Link to={`/home/message/detail/${msgObj.id}/${msgObj.title}`}>{msgObj.title}</Link>
              </li>
            );
          })}
        </ul>
		{/* 声明接受params参数 */}
        <Route path="/home/message/detail/:id/:title" component={Detail} />
      </div>
    );
  }
}

// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/24_src_路由query参数/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="msg in messageArr" :key="msg.id">
        <!-- 路由切换时，携带params参数 -->
        <!-- <router-link :to="`/home/message/detail/${msg.id}/${msg.title}/${msg.content}`">{{msg.title}}</router-link> -->

        <!-- 路由切换时，携带query参数 -->
        <router-link :to="`/home/message/detail/${msg.id}?title=${msg.title}&content=${msg.content}`">{{ msg.title }}
        </router-link>

      </li>
    </ul>
    <hr/>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'Message',
  data() {
    return {
      messageArr: [
        { id: '001', title: '消息1', content: '爱抽烟' },
        { id: '002', title: '消息2', content: '爱喝酒' },
        { id: '003', title: '消息3', content: '爱打麻将' },
      ]
    };
  }
};
</script>
