// atguigu/React/hacker-stories/src/pages/Home/Message/Detail/index.jsx
import React, { Component } from 'react'

const data = [
    {id: '01', content: '你好中国'},
    {id: '02', content: '你好英国'},
    {id: '03', content: '你好美国'},
]

export default class Detail extends Component {
  render() {
      console.log(this.props)
      const {id, title} = this.props.match.params
      const findResult = data.find((obj) => {
          return obj.id === id
      })
    return (
      <ul>
          <li>Id: {id}</li>
          <li>Tilte: {title}</li>
          <li>Content: {findResult.content}</li>
      </ul>  
    )
  }
}

// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/23_src_路由params参数/pages/Detail.vue
<template>
  <ul>
    <!-- 获取params参数 -->
    <li>ID：{{ id }}</li>
    <li>TITLE：{{ title }}</li>
    <li>CONTENT：{{ content }}</li>
  </ul>
</template>

<script>
export default {
  name: 'Detail',
  mounted() {
    console.log(this);
  },
  computed: {
    id() {
      return this.$route.params.id;
    },
    title() {
      return this.$route.params.title;
    },
    content() {
      return this.$route.params.content;
    },
  }
};
</script>
