// atguigu/React/源码/react_staging/03_src_TodoList案例/components/Item/index.jsx
import React, { Component } from 'react';
import './index.css';

export default class Item extends Component {

  state = { mouse: false }; //标识鼠标移入、移出

  //鼠标移入、移出的回调
  handleMouse = (flag) => {
    return () => {
      this.setState({ mouse: flag });
    };
  };

  //勾选、取消勾选某一个todo的回调
  handleCheck = (id) => {
    return (event) => {
      this.props.updateTodo(id, event.target.checked);
    };
  };

  //删除一个todo的回调
  handleDelete = (id) => {
    if (window.confirm('确定删除吗？')) {
      this.props.deleteTodo(id);
    }
  };


  render() {
    const { id, name, done } = this.props;
    const { mouse } = this.state;
    return (
      <li style={ { backgroundColor: mouse ? '#ddd' : 'white' } } onMouseEnter={ this.handleMouse(true) }
          onMouseLeave={ this.handleMouse(false) }>
        <label>
          <input type="checkbox" checked={ done } onChange={ this.handleCheck(id) }/>
          <span>{ name }</span>
        </label>
        <button onClick={ () => this.handleDelete(id) } className="btn btn-danger"
                style={ { display: mouse ? 'block' : 'none' } }>删除
        </button>
      </li>
    );
  }
}

// atguigu/Vue/尚硅谷vue2.0-vue3.0/staging/11_src_小复习/src_3/components/Item.vue
<template>
  <li>
    <label>
      <input type="checkbox" :checked="todo.done" @click="updateTodo(index,$event)"/>
      <span>{{ todo.name }}</span>
    </label>
    <button class="btn btn-danger" style="display:none">删除</button>
  </li>
</template>

<script>
export default {
  name: 'Item',
  props: ['todo', 'index', 'gengxinTodo'],
  methods: {
    updateTodo(index, event) {
      // console.log('updateTodo',index,event.target.checked)
      this.gengxinTodo(index, event.target.checked);
    }
  }
};
</script>

<style>
/*item*/
li {
  list-style: none;
  height: 36px;
  line-height: 36px;
  padding: 0 5px;
  border-bottom: 1px solid #ddd;
}

li label {
  float: left;
  cursor: pointer;
}

li label li input {
  vertical-align: middle;
  margin-right: 6px;
  position: relative;
  top: -1px;
}

li button {
  float: right;
  display: none;
  margin-top: 3px;
}

li:before {
  content: initial;
}

li:last-child {
  border-bottom: none;
}
</style>
